export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER = 'LOGIN_USER';

export const CLEAN_REDUCER_BY_REDUCER_NAME = 'CLEAN_REDUCER_BY_REDUCER_NAME';